all:


test3:
	./ascii_table.py --message 'oreno nichiyoubi kaeshiteeee lol'

test2:
	./ascii_table.py --message 'nani nani mou getsu youbi desutte orz'

test1:
	./ascii_table.py --message 'gomen na sai'
